#include "constants.h"

// Default initialization of physics constants
float INITIAL_MASS(DEFAULT_INITIAL_MASS);
float INITIAL_DAMPING(DEFAULT_INITIAL_DAMPING);
float COULOMB_CONSTANT(DEFAULT_COULOMB_CONSTANT);
float MAX_SPEED(DEFAULT_MAX_SPEED);
