#include "styles.h"

// Default initialization of colours
vec4f HOVERED_COLOUR(DEFAULT_HOVERED_COLOUR);
vec4f SELECTED_COLOUR(DEFAULT_SELECTED_COLOUR);
vec4f CLASSES_COLOUR(DEFAULT_CLASSES_COLOUR);
vec4f INSTANCES_COLOUR(DEFAULT_INSTANCES_COLOUR);
vec4f LITERALS_COLOUR(DEFAULT_LITERALS_COLOUR);
vec4f BACKGROUND_COLOUR(DEFAULT_BACKGROUND_COLOUR);
